### PR TITLE
Modernize BVLinearGradientLayer to use UIGraphicsImageRenderer if on supported OS versions

### LINKED ISSUE #618: Crash on iOS 17 Beta 2 and 3 compiled with iOS 17 SDK
When running a project that uses react-native-linear-gradient compiled in XCode 15 Beta 3 and iOS 17 Beta 3.

The exception in XCode when running in debug is 
```
reason	__NSCFString *	"UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={0, 0}, scale=3.000000, bitmapInfo=0x2006. Use UIGraphicsImageRenderer to avoid this assert."	0x000060000374f180
```

Looking at the call stack it fails on line 58 when calling UIGraphicsBeginImageContextWithOptions in BVLinearGradientLayer:
```
- (void)display {
    [super display];

    BOOL hasAlpha = NO;

    for (NSInteger i = 0; i < self.colors.count; i++) {
        hasAlpha = hasAlpha || CGColorGetAlpha(self.colors[i].CGColor) < 1.0;
    }

    UIGraphicsBeginImageContextWithOptions(self.bounds.size, !hasAlpha, 0.0);
    CGContextRef ref = UIGraphicsGetCurrentContext();
    [self drawInContext:ref];

    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    self.contents = (__bridge id _Nullable)(image.CGImage);
    self.contentsScale = image.scale;

    UIGraphicsEndImageContext();
}
```

This works on all previous versions of iOS 16, even when running on iOS 17 Beta 3, as long as it is not compiled against the iOS 17SDK.

referring to https://developer.apple.com/documentation/uikit/1623912-uigraphicsbeginimagecontextwitho. Even though UIGraphicsBeginImageContextWithOptions is still available in iOS 17, it is deprecated.

### PR DESCRIPTION
**Pull request by Caiopia**
When running on Xcode 15 against iOS 17 I'm getting a crash. It seems like the error message suggests `UIGraphicsBeginImageContext` isn't supported anymore and that we need to update to use `UIGraphicsImageRenderer` instead. I'm not sure if this assert only applies to specific cases internally, but I'm thinking it's probably a good idea to update to the more modern API anyways.

```
Thread 1: "UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={0, 6}, scale=3.000000, bitmapInfo=0x2006. Use UIGraphicsImageRenderer to avoid this assert."
```
<details>
<summary>Stack trace</summary>

```
*** Assertion failure in void _UIGraphicsBeginImageContextWithOptions(CGSize, BOOL, CGFloat, BOOL)(), UIGraphics.m:410
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={0, 6}, scale=3.000000, bitmapInfo=0x2006. Use UIGraphicsImageRenderer to avoid this assert.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000180465ef8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018005c0ac objc_exception_throw + 56
	2   Foundation                          0x0000000180caa400 -[NSMutableDictionary(NSMutableDictionary) classForCoder] + 0
	3   UIKitCore                           0x000000012e2f2d08 _UIGraphicsBeginImageContextWithOptions + 564
	4   MyAppFramework                      0x0000000119adf488 -[BVLinearGradientLayer display] + 576
	5   QuartzCore                          0x00000001884c4dec _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 392
	6   QuartzCore                          0x00000001883dfc68 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 460
	7   QuartzCore                          0x000000018840f65c _ZN2CA11Transaction6commitEv + 652
	8   QuartzCore                          0x0000000188410b10 _ZN2CA11Transaction25flush_as_runloop_observerEb + 68
	9   CoreFoundation                      0x00000001803c5cfc __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
	10  CoreFoundation                      0x00000001803c0700 __CFRunLoopDoObservers + 528
	11  CoreFoundation                      0x00000001803c0bb8 __CFRunLoopRun + 968
	12  CoreFoundation                      0x00000001803c03dc CFRunLoopRunSpecific + 572
	13  GraphicsServices                    0x0000000189bf5bc0 GSEventRunModal + 160
	14  UIKitCore                           0x000000012e737c70 -[UIApplication _run] + 868
	15  UIKitCore                           0x000000012e73b8d4 UIApplicationMain + 124
	16  MyApp                               0x000000010248cd38 main + 64
	17  dyld                                0x0000000110541558 start_sim + 20
	18  ???                                 0x0000000110629f28 0x0 + 4569866024
	19  ???                                 0x6d72800000000000 0x0 + 7886506634967515136
)
libc++abi: terminating due to uncaught exception of type NSException
```

</details>

I'd love some help testing this out to see if it changes any behaviours.

Fixes #618

### CODE REVIEW

**Comment by friederbluemle** [comment]
Thanks @Caiopia for taking time to submit a PR! 👍 

It sounds like this is directly related to an issue opened by @mwa3aan: #618

Right now I don't have the ability to test this, but just wanted to check how/if this patch would affect the compatibility with older versions of React Native/iOS/Xcode?

**Comment by mwa3aan** [comment]
@friederbluemle and @Caiopia I can confirm the changed resolved our issue I described in #618 

I tested it against xcode 15 beta 5 and ios SDK 17.

I don't have a machine with previous versions to test against. 

@Caiopia thanks for taking the time!!

**Comment by friederbluemle** [comment]
Awesome, thanks for the confirmation @mwa3aan!

I'd like to get this into the upcoming version 3.0.0 as well. We can do the testing together with all other changes in the default branch (namely new architecture support) using an alpha prerelease.

@Caiopia Can you rebase please and we'll get this merged.

**Comment by Caiopia** [comment]
Looks like none of the PR checks ended up running, is there a manual trigger for them?

**Comment by friederbluemle** [comment]
Perfect, thanks for the additional details @Caiopia

> Looks like none of the PR checks ended up running, is there a manual trigger for them?

I think it's because you're a first time contributor to this repo, I had to manually approve the CI run (a GitHub security thing I assume).

**Comment by Caiopia** [comment]
Ah hold on, we might need to take alpha into consideration. Give me a min.

**Comment by friederbluemle** [comment]
> Ah hold on, we might need to take alpha into consideration. Give me a min.

What do you mean? It looks good to me. Not ready for merge yet?

**Review by friederbluemle — APPROVED** [review]
:+1:

File: ios/BVLinearGradientLayer.m [hunk 1]
```diff
@@ -60,15 +60,32 @@ - (void)display {
...
-    CGContextRef ref = UIGraphicsGetCurrentContext();
-    [self drawInContext:ref];
+    if (@available(iOS 10.0, *)) {
+        UIGraphicsImageRendererFormat *format;
+        if (@available(iOS 11.0, *)) {
+            format = [UIGraphicsImageRendererFormat preferredFormat];
+        } else {
+            format = [UIGraphicsImageRendererFormat defaultFormat];
+        }
+        format.opaque = !hasAlpha;
```
Comment (Caiopia) [inline ios/BVLinearGradientLayer.m:70]: Previously the opaque field wasn't being set for the iOS 10+ flow. I think by default it's `false` with no `format` passed in.

Looking at the docs, [`defaultFormat`](https://developer.apple.com/documentation/uikit/uigraphicsrendererformat/1648550-default) seems like a decent option, but it points to [`preferredFormat`](https://developer.apple.com/documentation/uikit/uigraphicsrendererformat/2928214-preferred) for immediate rendering so I think that one should be the main choice. Though it's only available in iOS 11+ so that available check needs to be done again 😅.

**Comment by Caiopia** [comment]
Just added the setting of the opaque property. If you're happy with it feel free to merge it, otherwise I can pick this up again tomorrow.

File: ios/BVLinearGradientLayer.m (hunk 1 above)
Comment (friederbluemle) [reply ios/BVLinearGradientLayer.m:70]: Sounds good, thanks for the explanation!

Comment (iit2008047) [reply ios/BVLinearGradientLayer.m:70]: Can we publish a new version prior to 3.0.0 with this change ? .. iOS17 is around the corner

**Comment by iit2008047** [comment]
@friederbluemle  can we publish a new version with this change prior to 3.0.0 release. Thanks for all the help

File: ios/BVLinearGradientLayer.m (hunk 1 above)
Comment (friederbluemle) [reply ios/BVLinearGradientLayer.m:70]: @iit2008047 - Sure thing! It looks like the patch applies cleanly to the 2.8 branch. I'll cherry-pick it shortly and release the next 2.8 patch version (it will be 2.8.3).

**Comment by friederbluemle** [comment]
@iit2008047 https://github.com/react-native-linear-gradient/react-native-linear-gradient/releases/tag/v2.8.3 including this patch has been published.
